// AFeeree Certification Program - Real Course Data
// Based on "A-Feeree: The Physical Language" by BaKari Ifasegun Lindsay

import type { User, Module, Assignment, Notification } from './types';

// Google Drive Resource Links
export const resourceLinks = {
  notationImages: 'https://drive.google.com/file/d/1pq70_m7CfmQXsGW3qwstRpEaPriw2Buz/view?usp=drivesdk',
  syllabus: 'https://docs.google.com/document/d/15GxFM1saQj510YqpfFzvn68xMW7uQUyI/view',
};

// Seven Foundational Principles from Asante's African Culture Framework
export const foundationalPrinciples = [
  { name: 'Polyrhythm', description: 'Multiple distinct rhythms maintaining individual identity while creating unified expression' },
  { name: 'Polycentrism', description: 'Movement originating from multiple centers of the body simultaneously' },
  { name: 'Curvilinear Form', description: 'Emphasis on curved, flowing movement patterns' },
  { name: 'Dimensionality', description: 'Use of all spatial planes and levels in movement' },
  { name: 'Epic Memory', description: 'Connection to ancestral and cultural movement traditions' },
  { name: 'Repetition', description: 'Purposeful repetition for mastery and rhythmic grounding' },
  { name: 'Holism', description: 'Integration of mind, body, and spirit in movement practice' },
];

// Mandinka Terminology
export const mandinkaTerms = [
  { term: 'A-Feeree', meaning: 'Training/Method' },
  { term: 'Kunidi', meaning: 'Awakening' },
  { term: 'Kata', meaning: 'Movement' },
  { term: 'Bala', meaning: 'On' },
  { term: 'Barente', meaning: 'Move' },
  { term: 'Saba', meaning: 'Stretch' },
  { term: 'Semboo', meaning: 'Strength' },
  { term: 'Lapi', meaning: 'Beat' },
];

export const mockUser: User = {
  id: '1',
  name: 'Dance Student',
  email: 'student@example.com',
  enrollmentDate: '2024-01-15',
  certificationLevel: 'Foundation',
  progress: 35,
};

export const mockModules: Module[] = [
  {
    id: '1',
    title: 'Kunindi (Awakening)',
    description: 'Opening positions and foundational torso work. Learn the core principles of AFeeree rooted in African and African Diasporic dance aesthetics.',
    imageUrl: 'https://images.unsplash.com/photo-1508807526345-15e9b5f4eaff?w=800',
    duration: '4 weeks',
    lessons: 8,
    completedLessons: 5,
    isLocked: false,
    category: 'Technique',
  },
  {
    id: '2',
    title: 'Torso Development',
    description: 'Spiraling, contracting, and releasing movements. Master the two-sectional body approach: upper (torso, arms, head) and lower (pelvis, legs).',
    imageUrl: 'https://images.unsplash.com/photo-1547153760-18fc86324498?w=800',
    duration: '3 weeks',
    lessons: 6,
    completedLessons: 2,
    isLocked: false,
    category: 'Technique',
  },
  {
    id: '3',
    title: 'Foot Rhythms & Isolation',
    description: 'Isolation and coordination exercises. Develop polyrhythmic movement where feet maintain steady rhythm while other body parts layer additional complexity.',
    imageUrl: 'https://images.unsplash.com/photo-1524594152303-9fd13543fe6e?w=800',
    duration: '3 weeks',
    lessons: 7,
    completedLessons: 0,
    isLocked: false,
    category: 'Technique',
  },
  {
    id: '4',
    title: 'Traditional Squats',
    description: 'Functional movement patterns rooted in African dance traditions. Build strength and flexibility through traditional squat positions.',
    imageUrl: 'https://images.unsplash.com/photo-1518611012118-696072aa579a?w=800',
    duration: '2 weeks',
    lessons: 5,
    completedLessons: 0,
    isLocked: false,
    category: 'Technique',
  },
  {
    id: '5',
    title: 'Bala-Lapi (On Beat)',
    description: 'Polyrhythmic isolation work including hand circles, head/neck articulation, shoulder sequences, rib-cage movements, and windmill arm combinations.',
    imageUrl: 'https://images.unsplash.com/photo-1508700929628-666bc8bd84ea?w=800',
    duration: '5 weeks',
    lessons: 12,
    completedLessons: 0,
    isLocked: true,
    category: 'Technique',
  },
  {
    id: '6',
    title: 'Saba-Semboo (Stretch & Strength)',
    description: 'Functional stretching and strengthening exercises. Develop the physical foundation needed for advanced AFeeree practice.',
    imageUrl: 'https://images.unsplash.com/photo-1544367567-0f2fcb009e0b?w=800',
    duration: '4 weeks',
    lessons: 10,
    completedLessons: 0,
    isLocked: true,
    category: 'Technique',
  },
  {
    id: '7',
    title: 'Flat Backs with Ripples',
    description: 'Spinal articulation techniques. Learn to create wave-like movements through the spine for expressive and powerful movement.',
    imageUrl: 'https://images.unsplash.com/photo-1571019613454-1cb2f99b2d8b?w=800',
    duration: '3 weeks',
    lessons: 6,
    completedLessons: 0,
    isLocked: true,
    category: 'Technique',
  },
  {
    id: '8',
    title: 'Barente (Move)',
    description: 'Integration combinations bringing together all learned techniques. Create flowing movement sequences using AFeeree principles.',
    imageUrl: 'https://images.unsplash.com/photo-1509670572852-70fb0a2d6e67?w=800',
    duration: '6 weeks',
    lessons: 15,
    completedLessons: 0,
    isLocked: true,
    category: 'Technique',
  },
  {
    id: '9',
    title: 'Seven Foundational Principles',
    description: 'Deep study of Polyrhythm, Polycentrism, Curvilinear Form, Dimensionality, Epic Memory, Repetition, and Holism from Asante\'s African Culture framework.',
    imageUrl: 'https://images.unsplash.com/photo-1456513080510-7bf3a84b82f8?w=800',
    duration: '4 weeks',
    lessons: 7,
    completedLessons: 0,
    isLocked: true,
    category: 'Theory',
  },
  {
    id: '10',
    title: 'Teaching AFeeree Methodology',
    description: 'Learn to teach AFeeree using proper pedagogical approaches. Understand prerequisites, safety guidelines, and class structure.',
    imageUrl: 'https://images.unsplash.com/photo-1594737625785-a6cbdabd333c?w=800',
    duration: '5 weeks',
    lessons: 12,
    completedLessons: 0,
    isLocked: true,
    category: 'Teaching Practice',
  },
  {
    id: '11',
    title: 'Cultural Research & Context',
    description: 'Study the ethnographic research behind AFeeree from Senegal, The Gambia, Trinidad and Tobago, Haiti, and North American communities.',
    imageUrl: 'https://images.unsplash.com/photo-1481627834876-b7833e8f5570?w=800',
    duration: '4 weeks',
    lessons: 8,
    completedLessons: 0,
    isLocked: true,
    category: 'Research',
  },
];

export const mockAssignments: Assignment[] = [
  {
    id: '1',
    title: 'Kunindi Opening Sequence',
    description: 'Record a 5-minute video demonstrating the Kunindi (Awakening) opening positions and foundational torso work.',
    moduleId: '1',
    moduleName: 'Kunindi (Awakening)',
    dueDate: '2024-02-15',
    status: 'submitted',
    submittedDate: '2024-02-12',
    type: 'video',
  },
  {
    id: '2',
    title: 'Torso Isolation Practice',
    description: 'Submit a video demonstrating spiraling, contracting, and releasing movements with proper muscular engagement.',
    moduleId: '2',
    moduleName: 'Torso Development',
    dueDate: '2024-02-20',
    status: 'pending',
    type: 'video',
  },
  {
    id: '3',
    title: 'Polyrhythm Written Analysis',
    description: 'Write a reflection on how polyrhythm and polymetric patterns function in African music and dance.',
    moduleId: '9',
    moduleName: 'Seven Foundational Principles',
    dueDate: '2024-02-10',
    status: 'graded',
    submittedDate: '2024-02-08',
    grade: 'A',
    feedback: 'Excellent understanding of polyrhythmic structures and their cultural significance.',
    type: 'document',
  },
  {
    id: '4',
    title: 'Mandinka Terminology Quiz',
    description: 'Complete the written assessment on Mandinka terminology used in AFeeree practice.',
    moduleId: '1',
    moduleName: 'Kunindi (Awakening)',
    dueDate: '2024-02-25',
    status: 'pending',
    type: 'document',
  },
  {
    id: '5',
    title: 'Teaching Demo: Foot Rhythms',
    description: 'Record a 10-minute teaching demonstration of foot rhythm exercises using AFeeree methodology.',
    moduleId: '10',
    moduleName: 'Teaching AFeeree Methodology',
    dueDate: '2024-03-01',
    status: 'pending',
    type: 'teaching_demo',
  },
  {
    id: '6',
    title: 'Personal Journey Reflection',
    description: 'Write a reflective piece on your connection to Epic Memory and ancestral movement traditions.',
    moduleId: '9',
    moduleName: 'Seven Foundational Principles',
    dueDate: '2024-03-05',
    status: 'pending',
    type: 'reflection',
  },
];

export const mockNotifications: Notification[] = [
  {
    id: '1',
    title: 'New Grade Posted',
    message: 'Your Polyrhythm Written Analysis has been graded. You received an A!',
    date: '2024-02-11',
    read: false,
    type: 'grade',
  },
  {
    id: '2',
    title: 'Assignment Due Soon',
    message: 'Torso Isolation Practice is due in 3 days.',
    date: '2024-02-17',
    read: false,
    type: 'reminder',
  },
  {
    id: '3',
    title: 'New Resource Available',
    message: 'AFeeree Word Pages Notation PDF has been added to your resources.',
    date: '2024-02-15',
    read: true,
    type: 'announcement',
  },
  {
    id: '4',
    title: 'Live Session with BaKari Lindsay',
    message: 'Join the live Q&A session with founder BaKari Ifasegun Lindsay on February 22nd at 6pm EST.',
    date: '2024-02-18',
    read: false,
    type: 'announcement',
  },
];
