// Mock data for AFeeree Certification Program

import type { User, Module, Assignment, Notification } from './types';

export const mockUser: User = {
  id: '1',
  name: 'Dance Student',
  email: 'student@example.com',
  enrollmentDate: '2024-01-15',
  certificationLevel: 'Foundation',
  progress: 35,
};

export const mockModules: Module[] = [
  {
    id: '1',
    title: 'Foundation Movement',
    description: 'Core principles of AFeeree dance methodology, focusing on body awareness and fundamental techniques.',
    imageUrl: 'https://images.unsplash.com/photo-1518834107812-67b0b7c58434?w=800',
    duration: '4 weeks',
    lessons: 12,
    completedLessons: 8,
    isLocked: false,
    category: 'Technique',
  },
  {
    id: '2',
    title: 'Rhythm & Musicality',
    description: 'Understanding musical structure and developing rhythmic sensitivity in movement.',
    imageUrl: 'https://images.unsplash.com/photo-1547153760-18fc86324498?w=800',
    duration: '3 weeks',
    lessons: 9,
    completedLessons: 4,
    isLocked: false,
    category: 'Theory',
  },
  {
    id: '3',
    title: 'Teaching Fundamentals',
    description: 'Learn effective teaching methods, class structure, and student engagement strategies.',
    imageUrl: 'https://images.unsplash.com/photo-1524594152303-9fd13543fe6e?w=800',
    duration: '5 weeks',
    lessons: 15,
    completedLessons: 0,
    isLocked: false,
    category: 'Teaching Practice',
  },
  {
    id: '4',
    title: 'Advanced Choreography',
    description: 'Create compelling choreographic works using AFeeree principles and techniques.',
    imageUrl: 'https://images.unsplash.com/photo-1508700929628-666bc8bd84ea?w=800',
    duration: '6 weeks',
    lessons: 18,
    completedLessons: 0,
    isLocked: true,
    category: 'Technique',
  },
  {
    id: '5',
    title: 'Dance Research Methods',
    description: 'Academic approaches to dance research, documentation, and scholarly writing.',
    imageUrl: 'https://images.unsplash.com/photo-1456513080510-7bf3a84b82f8?w=800',
    duration: '4 weeks',
    lessons: 10,
    completedLessons: 0,
    isLocked: true,
    category: 'Research',
  },
];

export const mockAssignments: Assignment[] = [
  {
    id: '1',
    title: 'Movement Analysis Video',
    description: 'Record a 5-minute video demonstrating the core movement principles from Module 1.',
    moduleId: '1',
    moduleName: 'Foundation Movement',
    dueDate: '2024-02-15',
    status: 'submitted',
    submittedDate: '2024-02-12',
    type: 'video',
  },
  {
    id: '2',
    title: 'Teaching Practice Demo',
    description: 'Submit a 10-minute video of you teaching a beginner class using AFeeree methodology.',
    moduleId: '3',
    moduleName: 'Teaching Fundamentals',
    dueDate: '2024-02-20',
    status: 'pending',
    type: 'teaching_demo',
  },
  {
    id: '3',
    title: 'Rhythm Notation Exercise',
    description: 'Complete the written notation exercise for the provided musical piece.',
    moduleId: '2',
    moduleName: 'Rhythm & Musicality',
    dueDate: '2024-02-10',
    status: 'graded',
    submittedDate: '2024-02-08',
    grade: 'A',
    feedback: 'Excellent understanding of rhythmic structures. Your notation is clear and accurate.',
    type: 'document',
  },
  {
    id: '4',
    title: 'Personal Reflection Journal',
    description: 'Write a reflective piece on your journey through the foundation module.',
    moduleId: '1',
    moduleName: 'Foundation Movement',
    dueDate: '2024-02-25',
    status: 'pending',
    type: 'reflection',
  },
];

export const mockNotifications: Notification[] = [
  {
    id: '1',
    title: 'New Grade Posted',
    message: 'Your Rhythm Notation Exercise has been graded. You received an A!',
    date: '2024-02-11',
    read: false,
    type: 'grade',
  },
  {
    id: '2',
    title: 'Assignment Due Soon',
    message: 'Teaching Practice Demo is due in 3 days.',
    date: '2024-02-17',
    read: false,
    type: 'reminder',
  },
  {
    id: '3',
    title: 'New Announcement',
    message: 'Live Q&A session scheduled for February 22nd at 6pm EST.',
    date: '2024-02-15',
    read: true,
    type: 'announcement',
  },
];
